/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.micompania.nomina.vista;

import org.micompania.nomina.controlador.NominaControlador;

/**
 *
 * @author GTX1050
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private NominaControlador nominaActual;
    private VentanaDepartamento vDepto;
    private VentanaEmpleado vEmpleado;
    private VentanaSalario vSalario;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    public VentanaPrincipal(NominaControlador nominaActual) {
        this.nominaActual = nominaActual;
        initComponents();
        vDepto = new VentanaDepartamento(nominaActual);
        vEmpleado = new VentanaEmpleado(nominaActual);
        vSalario= new VentanaSalario(nominaActual);
    }
    
    public NominaControlador getNominaActual() {
        return nominaActual;
    }

    public void setNominaActual(NominaControlador nominaActual) {
        this.nominaActual = nominaActual;
    }

    public VentanaDepartamento getvDepto() {
        return vDepto;
    }

    public void setvDepto(VentanaDepartamento vDepto) {
        this.vDepto = vDepto;
    }
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDepartamento = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnContratista = new javax.swing.JButton();
        btnSalario = new javax.swing.JButton();
        btnListaNomina = new javax.swing.JButton();
        btnAcerca = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPagoContratista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Nomina Swing 1.0");

        btnDepartamento.setText("Agregar Departamento");
        btnDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDepartamentoMouseClicked(evt);
            }
        });

        btnEmpleado.setText("Agregar Empleado");
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseClicked(evt);
            }
        });

        btnContratista.setText("Agregar Contratista");
        btnContratista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratistaActionPerformed(evt);
            }
        });

        btnSalario.setText("Agregar Salario");
        btnSalario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalarioMouseClicked(evt);
            }
        });

        btnListaNomina.setText("Listar Nomina Mes");
        btnListaNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaNominaActionPerformed(evt);
            }
        });

        btnAcerca.setText("Acerca de ...");
        btnAcerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcercaMouseClicked(evt);
            }
        });
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPagoContratista.setText("Act.Pago Contratista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnDepartamento)
                    .addComponent(btnEmpleado)
                    .addComponent(btnContratista)
                    .addComponent(btnPagoContratista, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalario)
                    .addComponent(btnListaNomina)
                    .addComponent(btnAcerca)
                    .addComponent(btnSalir))
                .addGap(107, 107, 107))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAcerca, btnContratista, btnDepartamento, btnEmpleado, btnListaNomina, btnPagoContratista, btnSalario, btnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalario)
                .addGap(35, 35, 35)
                .addComponent(btnContratista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagoContratista)
                .addGap(24, 24, 24)
                .addComponent(btnListaNomina)
                .addGap(30, 30, 30)
                .addComponent(btnAcerca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAcerca, btnContratista, btnDepartamento, btnEmpleado, btnListaNomina, btnPagoContratista, btnSalario, btnSalir});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContratistaActionPerformed

    private void btnListaNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaNominaActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepartamentoMouseClicked
        vDepto.setVisible(true);
    }//GEN-LAST:event_btnDepartamentoMouseClicked

    private void btnEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseClicked
        vEmpleado.llenarListaDepartamentos();
        vEmpleado.llenarSalarios();
        vEmpleado.setVisible(true);
    }//GEN-LAST:event_btnEmpleadoMouseClicked

    private void btnSalarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalarioMouseClicked
        vSalario.setVisible(true);
    }//GEN-LAST:event_btnSalarioMouseClicked

    private void btnAcercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcercaMouseClicked
        new VentanaAcerca().setVisible(true);
    }//GEN-LAST:event_btnAcercaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnContratista;
    private javax.swing.JButton btnDepartamento;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnListaNomina;
    private javax.swing.JButton btnPagoContratista;
    private javax.swing.JButton btnSalario;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the vSalario
     */
    public VentanaSalario getvSalario() {
        return vSalario;
    }

    /**
     * @param vSalario the vSalario to set
     */
    public void setvSalario(VentanaSalario vSalario) {
        this.vSalario = vSalario;
    }
}
