/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.micompania.nomina.vista;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.micompania.nomina.controlador.NominaControlador;
import org.micompania.nomina.modelo.Departamento;
import org.micompania.nomina.modelo.Empleado;
import org.micompania.nomina.modelo.Persona;
import org.micompania.nomina.util.NominaException;
import org.micompania.nomina.util.UtilidadesVista;
import org.micompania.nomina.vista.modelos.ModeloTablaEmpleado;

/**
 *
 * @author GTX1050
 */
public class VentanaMostrarEmpleado extends javax.swing.JFrame {
    private NominaControlador nomina;
    private ModeloTablaEmpleado modeloTabla;
    /**
     * Creates new form VentanaMostrarEmpleado
     */
    public VentanaMostrarEmpleado() {
        initComponents();
    }
    
    private List<Empleado> obtenerTodosLosEmpleados(){
        try {
            List<Empleado> todos = new ArrayList<>();
            for(Departamento depto : nomina.obtenerTodosLosDepartamentos()){
                for(Persona p : depto.getPersonas()){
                    if(p instanceof Empleado){
                        todos.add((Empleado) p);
                    }
                }
            }
            return todos;
        } catch (NominaException ex) {
            UtilidadesVista.mostrarMensajeError(this, ex.getMessage());
            return null;
        }
    }

    public VentanaMostrarEmpleado(NominaControlador nomina) {
        this.nomina = nomina;
        initComponents();
        modeloTabla = new ModeloTablaEmpleado(this.obtenerTodosLosEmpleados());
        tblListaEmpleados.setModel(modeloTabla);
    }

    public NominaControlador getNomina() {
        return nomina;
    }

    public void setNomina(NominaControlador nomina) {
        this.nomina = nomina;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaEmpleados = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTA DE EMPLEADOS");

        jScrollPane1.setViewportView(tblListaEmpleados);

        jButton1.setText("Cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaEmpleados;
    // End of variables declaration//GEN-END:variables
}
